![](https://import.cdn.thinkific.com/220744/BExaQBPPQairRWFqxFbK_logo_mastermind_web_png)

numpy nos ayudará con computación numerica y se importa así:

In [3]:
import numpy as np

In [2]:
np.sqrt(25) #ejemplo de contenido en numpy, función para sacar raaíz

5.0

# Arrays

## np.array()

In [16]:
a = [0, 1, 2, 3, 4, 5]

type(a)

list

In [4]:
type(np.array(a))

numpy.ndarray

## np.arange()

In [6]:
b = np.arange(4, 24, 2) #Imprimo de dos en dos puesto que eso me lo indica al final
                        #pero empezando con 4 y limite 24 
print(b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linspace()

In [13]:
c = np.linspace(1, 500, 20) #Te genera en espacios iguales los numero dependiendo del limite

print(c)

[  1.          27.26315789  53.52631579  79.78947368 106.05263158
 132.31578947 158.57894737 184.84210526 211.10526316 237.36842105
 263.63157895 289.89473684 316.15789474 342.42105263 368.68421053
 394.94736842 421.21052632 447.47368421 473.73684211 500.        ]


## np.zeros()

In [4]:
d = np.zeros(50) # practicamente imprime la cantidad de ceros

print (d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


## np.ones()

In [5]:
e = np.ones(50) 

print(e)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


# Dimensiones

In [6]:
array_2d = np.array([d, e]) #me traigo 2 arrays para imprimirlos juntos

In [18]:
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [19]:
array_2d.shape ## Si das tab después del punto, te aparecen las opciones a elegir! :o
               ## a sicierto, con este vemos su detalle de shape 

(2, 50)

## array.size

In [20]:
array_2d.size #ver total de dimensiones

100

## array.ndim

In [21]:
array_2d.ndim #para ver dimensiones

2

## Operaciones con arrays

In [38]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [39]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [40]:
lista_1 + lista_2 #aquí sumamos las listas pero lo que hace es unirlas, por defecto 
                  #Python no te puede hacer sumas aritmeticas, pero numpy si con arrays

[1, 2, 3, 4, 5, 6]

In [41]:
array_1 + array_2 #Y este sería el meétodo

array([5, 7, 9])

In [42]:
array_1 * array_2

array([ 4, 10, 18])

In [43]:
#ahora lo mismo pero con el metodo arcaico y dificil, con list comprehensions
[ num1*num2 for num1, num2 in zip(lista_1, lista_2)]

[4, 10, 18]

# Funciones

## np.reshape()

In [8]:
array_2d.shape

(2, 50)

In [10]:
f = np.reshape(array_2d, (1, 100)) # aquí pone todos los elementos en 1 sola dimensión

In [11]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [14]:
f = np.reshape(array_2d, (5, 20)) #aquí lo reaorganiza para tenerlo de 5 dimensiones con 20 valores

In [15]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

Ojo, tienen que ser divisibles el total de elementos entre la cantidad de dimensiones y valores que le des, si le das de más o de menos y no es divisible, marca error

## array.T

In [17]:
a = np.array ([1, 2, 3, 4, 5])

In [18]:
a.T

array([1, 2, 3, 4, 5])

No pasa aparentemente nada puesto que es de una dimensión, provemos con 2 dimensiones

In [19]:
a = np.array ([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])

a.shape

(2, 5)

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

Ya que tenemos uno por ejemplo de 2 dimensiones, podemos usar array.T, para hacer una transposición

In [21]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

## np.random

### np.random.randint

In [23]:
np.random.randint(0, 300) #Genera numero aleatorio dandole un rango

182

## np.where

In [24]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [25]:
np.where(array_2d == 1, array_2d *10, array_2d -5 )

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

Si no entendiste muy bien lo que pasó arriba, fue lo siguiente, modificamos los valores de los arrays utilizando iteración con where.
Poniendo el código pero con texto esto fue lo que pasó:

usando where( en valores del array lo que sea igual = a 1, ese valor del array multiplicalo x 10, lo que no de esos valores restale 5)

# Estadistica

## Distribuciones

Aquí suponiendo que hacemos una ditribución normal, en la que la media de alturas en 1000 individuos es de 1,75mts, con una desviación estandar de 5cm
(el primer paramtero debe ser la media, el segundo la desviación y el tercero la cantidad de datos a generar)

In [26]:
array_normal = np.random.normal(1.75, 0.05, 1000)

In [27]:
array_normal

array([1.68694316, 1.77045061, 1.70414363, 1.73012808, 1.69098511,
       1.72654967, 1.78503813, 1.67234208, 1.68151901, 1.72119991,
       1.80652649, 1.64572727, 1.70776354, 1.85027977, 1.78212658,
       1.68668205, 1.74785444, 1.71867616, 1.69801035, 1.77708825,
       1.7489902 , 1.72826165, 1.77732508, 1.75907027, 1.75565769,
       1.88421341, 1.72582533, 1.72932741, 1.67185876, 1.78042614,
       1.75288732, 1.79214143, 1.72832754, 1.68317903, 1.80465695,
       1.78513712, 1.81139111, 1.76652347, 1.73862351, 1.76870085,
       1.70066673, 1.72568383, 1.76582013, 1.71048036, 1.71030739,
       1.79175023, 1.77069818, 1.85319227, 1.73044487, 1.78654695,
       1.73067961, 1.78787704, 1.84709583, 1.73128351, 1.68632712,
       1.74350159, 1.75227469, 1.68591855, 1.74922946, 1.71933087,
       1.65955111, 1.75440269, 1.76470542, 1.72915762, 1.77554169,
       1.78263082, 1.74370049, 1.81870935, 1.71023358, 1.73192622,
       1.68807732, 1.77516153, 1.73997887, 1.85869193, 1.73252

## np.mean

In [28]:
np.mean(array_normal) #Con esto sacamos la media de una distribución

1.748486923805684

## np.median

In [29]:
np.median(array_normal) #Sacar la mediana, que el es valor centro de una distribución

1.7466961204212583

## np.std

In [30]:
np.std(array_normal) #Sacar la desviación estandar si esta no fue dada

0.046995167804897604