In [1]:
import numpy as np #numpy nos ayudará con computación numerica

In [2]:
np.sqrt(25)

5.0

# Arrays

## np.array()

In [3]:
a = [0, 1, 2, 3, 4, 5]

type(a)

list

In [4]:
type(np.array(a))

numpy.ndarray

## np.arange()

In [6]:
b = np.arange(4, 24, 2) #Imprimo de dos en dos puesto que eso me lo indica al final
                        #pero empezando con 4 y limite 24 
print(b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linspace()

In [13]:
c = np.linspace(1, 500, 20) #Te genera en espacios iguales los numero dependiendo del limite

print(c)

[  1.          27.26315789  53.52631579  79.78947368 106.05263158
 132.31578947 158.57894737 184.84210526 211.10526316 237.36842105
 263.63157895 289.89473684 316.15789474 342.42105263 368.68421053
 394.94736842 421.21052632 447.47368421 473.73684211 500.        ]


## np.zeros()

In [14]:
d = np.zeros(50) # practicamente imprime la cantidad de ceros

print (d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


## np.ones()

In [16]:
e = np.ones(50) 

print(e)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


# Dimensiones

In [17]:
array_2d = np.array([d, e]) #me traigo 2 arrays para imprimirlos juntos

In [18]:
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [19]:
array_2d.shape ## Si das tab después del punto, te aparecen las opciones a elegir! :o
               ## a sicierto, con este vemos su detalle de shape 

(2, 50)

## array.size

In [20]:
array_2d.size #ver total de dimensiones

100

## array.ndim

In [21]:
array_2d.ndim #para ver dimensiones

2

## Operaciones con arrays

In [38]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [39]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [40]:
lista_1 + lista_2 #aquí sumamos las listas pero lo que hace es unirlas, por defecto 
                  #Python no te puede hacer sumas aritmeticas, pero numpy si con arrays

[1, 2, 3, 4, 5, 6]

In [41]:
array_1 + array_2 #Y este sería el meétodo

array([5, 7, 9])

In [42]:
array_1 * array_2

array([ 4, 10, 18])

In [43]:
#ahora lo mismo pero con el metodo arcaico y dificil, con list comprehensions
[ num1*num2 for num1, num2 in zip(lista_1, lista_2)]

[4, 10, 18]